# Generated by Django 5.0.6 on 2024-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('cars', '0002_remove_car_accounts_remove_car_brand_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='brands.brand'),
        ),
    ]
